INSERT INTO USERS2(USERNAME,HASHPASSWORD) VALUES('Mark','Password1');
INSERT INTO USERS2(USERNAME,HASHPASSWORD) VALUES('Ken','Password2');
INSERT INTO USERS2(USERNAME,HASHPASSWORD) VALUES('Peter','Password3');
INSERT INTO USERS2(USERNAME,HASHPASSWORD) VALUES('Tim','Password4');